### ISSUE TITLE
Static Image not recognize from CBAnim

### ISSUE THREAD

**Issue by seewood** [SKGleba/PSP2-CBAnim#4]
Hey SKGleba, thanks for the nice work!
i want to set a Still Image to my Start Screen but i cannot convert it to boot_splash.img with cbanim.

convert.exe and gzip.exe are in the same folder with the cbanim.exe and the moon.jpg Image

my command line is:
cbanim -p moon.jpg
ENTER
nothing happend, i get the manual from cbanim. 

What i'm doing wrong? with a .gif file it works flawless and i get the boot_animation.img file at the end

**Comment by SKGleba** [comment]
I will fix it in the next update, remove the 'gif' check from https://github.com/SKGleba/PSP2-CBAnim/blob/c1c27cd458339284f4b0c5df39df660c34ccf23d/linux/main.c#L63

**Comment by seewood** [comment]
i'm using Windows, you linked Line 63 in linux/main.c
I think it should be changed in both win and linux.
